# Generated by Django 5.0.3 on 2024-05-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
